### ISSUE TITLE
Links über

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-python-editor#1]
Wenn man auf about drückt, und dann auf über geht, steht ganz unten folgender Text:
MicroPython [Quellcode für den Calliope mini V1.x-V2.x](https://github.com/bbcmicrobit/micropython) und [micro:bit V2](https://github.com/microbit-foundation/micropython-microbit-v2)
[Erfahre, wie es zu MicroPython kam](https://ntoll.org/article/story-micropython-on-microbit/)

Bitte entfernen

**Comment by maluramichael** [comment]
Ich hab den zweiten Link auch entfernt weil der auf https://ntoll.org/article/story-micropython-on-microbit/ gezeigt hat.

![image](https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/5c6dd03f-01f2-4b5c-97d3-a5fa8629cd59)
