### ISSUE TITLE
Changes of strings

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-python-editor#10]
When translating the strings I found several wrong items. So far it is:
Often it says V2, but need to be V3
Sometimes it happens that BBC is included, but should be deleted.

Get the temperature of the micro:bit in degrees Celcius.
calliopemini.temperature.summary

MicroBitDigitalPin
Some pins support analog and touch features using the MicroBitAnalogDigitalPin and MicroBitTouchPin subclasses.

MicroBitAnalogDigitalPin
base class [MicroBitDigitalPin](https://python.calliope.cc/reference/radio#calliopemini.MicroBitDigitalPin)

MicroBitTouchPin
base class [MicroBitAnalogDigitalPin](https://python.calliope.cc/reference/radio#calliopemini.MicroBitAnalogDigitalPin)

microbittouchpin

A touch sensitive logo pin on the front of the micro:bit, which by default is set to capacitive touch mode.

A pin to address the micro:bit speaker.

An image to show on the micro:bit LED display.

Measure the acceleration of the micro:bit and recognise gestures.

**Comment by maluramichael** [comment]
@joernalraun Um das ein bisschen aufzudroeseln

- Often it says V2, but need to be V3
Sometimes it happens that BBC is included, but should be deleted.
  - **Du meinst sowas hier in den Translations oder? BBC habe ich jetzt nicht sofort gefunden. Das musst du mir nochmal kurz hier zeigen.**
![image](https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/46791987-29ab-46fb-99d6-9351d1f70dbe)
- Get the temperature of the micro:bit in degrees Celcius.
calliopemini.temperature.summary
  - **Micro:bit finde ich auch noch oft in den Stubs. Das kann ich durch Calliope ersetzen. Oder doch durch etwas anderes?**
![image](https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/3b1ae750-3856-4e15-923e-fe91d00d37c5)
- MicroBit*Pin Subclasses
  - **Die Klassen kann ich in den Typeshed Files umbenennen. Ich kann mir aber vorstellen dass das eure Hex auch koennen muss. @fabianhugo weisst du ob du einfach so was umbenennen kannst?**
- Rest
  - **Alles andere sind einfach nur Strings die du gefunden hast right?**

**Comment by fabianhugo** [comment]
- Das wär super, hier in den Stubs das micro:bit durch Calliope mini auszutauschen. Außerdem, da wo micro:bit V1 steht ein Calliope mini V1,V2 zu machen und da wo micro:bit V2 steht Calliope mini V3 zu schreiben.
- Zu den Subclasses: Das stimmt, viele von denen waren bereits angepasst. Eine Anpassung muss ich jedoch noch machen. Ich geb nochmal Bescheid, wenn die durch ist.

**Comment by maluramichael** [comment]
Zu was soll ich MicroBitDigitalPin, MicroBitAnalogDigitalPin und MicroBitTouchPin umbenennen? Sollte man hier vielleicht einfach den Prefix MicroBit ganz weglassen? Kommt mir komisch vor nur die Pins zu prefixen

**Comment by fabianhugo** [comment]
Alles was nicht sichtbar ist, belassen wir meistens in dem Zustand, damit wir das besser warten können. Das wären sonst an vielen Stellen tiefgreifende Änderungen. Also gerne bei: MicroBitDigitalPin, MicroBitAnalogDigitalPin und MicroBitTouchPin belassen

**Comment by maluramichael** [comment]
hmm also die Klassen sind teilweise sichtbar. Glaube darum hat @joernalraun das angesprochen.

![image](https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/b11538aa-365e-4129-8752-75208c0d6c81)

**Comment by fabianhugo** [comment]
Ah, verstehe. @joernalraun ist glaube ich gerade unterwegs, kann aber wahrscheinlich heut Nachmittag nochmal reinschauen. 
Hast du die Klassen schon einmal probeweise geändert?
Dieses "MicroBit" im Klassenname scheint ja nur bei bei diesen 3 Klassen vorzukommen. Mir scheint dein Vorschlag gut, das "MicroBit" wegzulassen

**Comment by maluramichael** [comment]
Ich probier es mal aus. Japp das sind nur die 3 Klassen. Also theoretisch nicht so uebel.

**Comment by maluramichael** [comment]
Also so an sich wuerde es gehen. Die Hex muss es halt noch koennen 
![image](https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/27a9e26e-0e6f-4754-8b5e-78cbf7544f4f)

**Comment by fabianhugo** [comment]
Ah cool. Dieses Hex sollte es eigentlich können: 
https://github.com/calliope-edu/micropython-calliope-mini-v3/actions/runs/6560703319
Aber ich kann weder die alten Pin Klassen Namen noch die neuen verwenden. Kannst du das kurz testen?

**Comment by maluramichael** [comment]
Du hast recht. Auf Staging kann ich auch kein MicroBit*Pin verwenden. Vielleicht war das nie angedacht.

![image](https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/c9941e6e-3ebc-48f3-b63c-1783438b53b3)

**Comment by fabianhugo** [comment]
Interessant. Ja das kann ich mir gut vorstellen, hab dazu auch kein Eintrag in der Api gefunden.

Update: Im Live Microbit Editor sind die schon verwendbar.
Update2: Aber das Microbit Hex File kennt sie auch nicht.

Also würde die so lassen und wenn möglich verstecken.

**Comment by joernalraun** [comment]
Hey, klingt alles super!
Ich bin mir gerade unsicher, ob ich damit auch nur die Headlines bei der API meinte. Muss ich nachher nochmal checken!

**Comment by fabianhugo** [comment]
Ich hab die Klassennamensänderung wieder rückgängig gemacht und zudem den Namen des generierten Hex Files angepasst. Und das alles in den branch v2.1.1-cmini3 gepusht. Hier ist der Link zur Action: https://github.com/calliope-edu/micropython-calliope-mini-v3/actions/runs/6562123852

**Comment by joernalraun** [comment]
> @joernalraun Um das ein bisschen aufzudroeseln
> 
> * Often it says V2, but need to be V3
>   Sometimes it happens that BBC is included, but should be deleted.
>   
>   * **Du meinst sowas hier in den Translations oder? BBC habe ich jetzt nicht sofort gefunden. Das musst du mir nochmal kurz hier zeigen.**
>     ![image](https://user-images.githubusercontent.com/1489383/276151247-46791987-29ab-46fb-99d6-9351d1f70dbe.png)
> * Get the temperature of the micro:bit in degrees Celcius.
>   calliopemini.temperature.summary
>   
>   * **Micro:bit finde ich auch noch oft in den Stubs. Das kann ich durch Calliope ersetzen. Oder doch durch etwas anderes?**

>   
>   * **Alles andere sind einfach nur Strings die du gefunden hast right?**

Ja, genau! Weitere kleine Fehler in Strings sammele ich hier:
https://github.com/calliope-edu/calliope-mini-python-editor/issues/12

**Comment by maluramichael** [comment]
Alles klar dann mach ich hier mal zu
