### ISSUE TITLE
"Pins" bei Referenz auf Englisch anklicken führt zu Fehlermeldung

### ISSUE THREAD

**Issue by fabianhugo** [calliope-edu/calliope-mini-python-editor#11]
Wenn die Sprache auf Englisch eingestellt ist, und die Kategorie Pins angeklickt wird, erscheint die folgende Fehlermeldung. Daraufhin werden die Referenzblöcke nicht mehr angezeigt, nur ein Neuladen der Seite lässt die Referenzblöcke wieder funktionieren. Die Pins Kategorie bleibt auf Englisch jedoch nicht verwendbar.  Auf deutsch gibt es dieses Problem nicht.
![grafik](https://github.com/calliope-edu/calliope-mini-python-editor/assets/32654742/8c1fc99c-00c6-41fa-ae01-15e87e0a001d)
OS: Ubuntu 20.04
Browser: Chrome Version 118.0.5993.70 (Offizieller Build) (64-Bit)

**Comment by maluramichael** [comment]
Hast du den Editor gerade da bei dir lokal laufen?

**Comment by fabianhugo** [comment]
ne, bei https://staging.python.calliope.cc/

**Comment by maluramichael** [comment]
Jetzt geht es wieder.
![image](https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/d6e166d1-2e17-4394-a795-ff806311659f)

Der neue Pin3 hatte keinen Slug
![image](https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/f0211ee7-1f79-4e88-bd4d-e2a924e056f4)
