### ISSUE TITLE
micropython HEX file Update für calliope mini 3

### ISSUE THREAD

**Issue by fabianhugo** [calliope-edu/calliope-mini-python-editor#13]
Derzeit ist noch ein älteres Hex File hinterlegt, in welchem z.B. die Motorpins noch die alten Namen tragen (M_A_IN...). 
Das micropython Hex wurde nochmal überarbeitet und findet sich unter diesem Link: 
https://github.com/calliope-edu/micropython-calliope-mini-v3/actions/runs/6706098696

**Comment by maluramichael** [comment]
@fabianhugo hast du eine neue HEX file die ich adden sollte? glaub die in deinem kommentar ist nicht mehr aktuell oder?

**Comment by fabianhugo** [comment]
Hi Michael, derzeit ist das die Aktuellste. Ist dir an der etwas aufgefallen?

**Comment by maluramichael** [comment]
Schau ich gleich mal. Ich bau sie naemlich gerade fuer den Release ein.

**Comment by maluramichael** [comment]
Hab die HEX jetzt gepushed. Dauert noch bisschen bis die Actions durchgelaufen sind.
