### ISSUE TITLE
Sammlung von Verbesserungen bei Bezeichnungen

### ISSUE THREAD

**Issue by fabianhugo** [calliope-edu/calliope-mini-python-editor#14]
Der Editor unter staging sieht schon echt gut aus und macht richtig Spaß.  Ein paar Punkte sind mir noch aufgefallen: 
1. Referenz/RGB-LEDs
die Blöcke funktionieren gut. Nur der pin_RGB erscheint noch unterringelt
![grafik](https://github.com/calliope-edu/calliope-mini-python-editor/assets/32654742/682928a1-f6ad-41cb-bd8f-b1ad11076c4e)
2. API/calliopemini
die Blöcke hier laden jedes mal den Textbaustein __import calliopemini__ zusätzlich in den Editor. Das ist eine Dopplung, da die Befehle schon über __from calliopemini import *__ zur Verfügung stehen. 
![grafik](https://github.com/calliope-edu/calliope-mini-python-editor/assets/32654742/3d583221-bcf3-4975-a8b9-7b02b3b2d2ec)
Diese Blöcke sollten auch den Textbaustein __from calliopemini import *__ verwenden, dann könnten die eigentlichen Befehlsblöcke auch gekürzt werden. Von z.B. __calliopemini.panic(20)__ zu __panic(20)__. Im microbit Editor wird das auch in der verkürzten Form verwendet. 
3. API/calliopemini 
bei den Klassen MicroBitDigitalPin, MicroBitAnalogDigitalPin, MicroBitTouchPin steht noch MicroBit. Da wollten wir die das MicroBit weglassen oder? 

4. API/calliopemini
Pin3 ist nicht analog und sollte sein "Pin mit digitalen und und Touch Funktionen"
![grafik](https://github.com/calliope-edu/calliope-mini-python-editor/assets/32654742/5fe1924d-b653-4e0d-90d6-197fd7f05b4c)

5. API/calliopemini
Pin18 fehlt. Ist ein "Pin mit digitalen und analogen Funktionen"
6. API/audio 
Der zweite Satz: "(Import audio für V1/V2, V3 Kompatibilität)" sollte entfernt werden. Auf V1 und V2 funktioniert audio derzeit mit micropython nicht.
![grafik](https://github.com/calliope-edu/calliope-mini-python-editor/assets/32654742/9028d3f4-9976-46c7-a7f2-f88e3f149905)

**Comment by joernalraun** [comment]
calliopemini.pin_A1_RX ist analog und digital

**Comment by maluramichael** [comment]
1. der RGB Pin ist bei mir untergegangen Sorry.
2. Das ist ein "Bug" in den Sanity Translations. Einfach in Sanity den Codebaustein anpassen.
3. Dachte eigentlich wir hatten uns drauf geeinigt die so zu lassen.
4. Im Code gibt es folgende Klassen MicroBitDigitalPin, MicroBitAnalogDigitalPin, MicroBitTouchPin. Der MicroBitTouchPin erbt von MicroBitAnalogDigitalPin. Einen nur digital + Touch gibt es so nicht. Gibt es den schon in der Hex File? Dann koennte ich versuchen diesen zu adden.
5. dachte ich haette den mit den Motorpins geadded. Kann man schnell hinzufuegen.
6. Das laesst sich schnell in Sanity anpassen

**Comment by fabianhugo** [comment]
Klingt gut, danke.
zu 3. Du hast recht, Entschuldige, hatte ich falsch abgespeichert.

edit: Können wir das mit dem hex austauschen auch machen? Kannst du uns das zeigen?
edit2: Hier sollte schon immer 3. stehen, statt 4. Sorry!

**Comment by maluramichael** [comment]
@fabianhugo eigentlich nicht schwer. Ihr muesst nur die Hex bauen (oder aus den Assets ziehen), die File umbenennen und dann diese Datei hier ersetzen. https://github.com/calliope-edu/calliope-mini-python-editor/blob/feature/calliope-rework/src/micropython/main/calliope-v3.hex

Commit, Push und Done

**Comment by maluramichael** [comment]
Und im Simulator einmal in dieses Verzeichnis hier gehen und das Submodule auf die entsprechende Version setzten https://github.com/calliope-edu/micropython-simulator/tree/feature/calliope-rework/lib

Commit, Push und Done

**Comment by maluramichael** [comment]
Ich plane mal 1 und 5 bei uns im Jira ein. Was ist mit Punkt 4 @fabianhugo passen wir die Klassen noch an?

**Comment by fabianhugo** [comment]
Ah, da hatte ich mich falsch erinnert. Nein, lass uns die Klassen so belassen.

**Comment by joernalraun** [comment]
@maluramichael und @fabianhugo 
pin_M_MODE
pin_M0_DIR
pin_M1_DIR
pin_M0_SPEED
pin_M1_SPEED
pin_RGB
werden auch noch als fehlerhaft gekennzeichnet.

**Comment by fabianhugo** [comment]
Wenn die is_touched() Funktion mit Pin3 verwendet wird, wird diese noch als unterringelt dargestellt.
![grafik](https://github.com/calliope-edu/calliope-mini-python-editor/assets/32654742/e90897a5-882e-4ffb-a3b6-5fe04aab61dd)

**Comment by maluramichael** [comment]
@joernalraun der pin_M_Mode Pin heisst eigentlich pin_M_MODE https://github.com/calliope-edu/calliope-mini-python-editor/issues/6#issuecomment-1767945091

So sehen die Pins jetzt bei mir aus 
<img width="865" alt="image" src="https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/b3a379f7-c376-4b6e-b5f1-68afa7c9af44">

**Comment by joernalraun** [comment]
> @joernalraun der pin_M_Mode Pin heisst eigentlich pin_M_MODE [#6 (comment)](https://github.com/calliope-edu/calliope-mini-python-editor/issues/6#issuecomment-1767945091)
> 
> So sehen die Pins jetzt bei mir aus <img alt="image" width="865" src="https://user-images.githubusercontent.com/1489383/282710020-b3a379f7-c376-4b6e-b5f1-68afa7c9af44.png">

Ja, richtig! Ich habe es aktualisiert!

**Comment by joernalraun** [comment]
@maluramichael as for number 2 I don't see an option/error for this in Sanity. Can you clarify this a bit?

**Comment by maluramichael** [comment]
@joernalraun das muesst ihr hier anpassen. Ich weiss nur nicht welcher API Eintrag falsch war. Aber wenn man das weiss dann kann man den einfach in Sanity anpassen.

<img width="1757" alt="image" src="https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/a8399e38-3c0c-4a73-8ef2-f635da53bf17">

**Comment by joernalraun** [comment]
> @joernalraun das muesst ihr hier anpassen. Ich weiss nur nicht welcher API Eintrag falsch war. Aber wenn man das weiss dann kann man den einfach in Sanity anpassen.
> 
> <img alt="image" width="1757" src="https://user-images.githubusercontent.com/1489383/284162899-a8399e38-3c0c-4a73-8ef2-f635da53bf17.png">

Ich glaube nicht. Es sind z.B. die Buttons, aus der API. Da steht nichts falsches in Sanity, soweit ich das sehe.

**Comment by joernalraun** [comment]
> > @joernalraun das muesst ihr hier anpassen. Ich weiss nur nicht welcher API Eintrag falsch war. Aber wenn man das weiss dann kann man den einfach in Sanity anpassen.
> > <img alt="image" width="1757" src="https://user-images.githubusercontent.com/1489383/284162899-a8399e38-3c0c-4a73-8ef2-f635da53bf17.png">
> 
> Ich glaube nicht. Es sind z.B. die Buttons, aus der API. Da steht nichts falsches in Sanity, soweit ich das sehe.

@maluramichael Es ist anscheinend überall, wo calliopemini in der API steht... Ich weiß aber nicht, ob ich das überhaupt ändern kann.

**Comment by maluramichael** [comment]
@joernalraun @fabianhugo hab Punkt 2 loesen koennen. Das war doch kein Problem in Sanity. https://github.com/calliope-edu/calliope-mini-python-editor/commit/4db3fcca2598377925ef2df753832b45f42599c7

**Comment by maluramichael** [comment]
Hier sollten jetzt auch alle Changes auf Production sein. Einfach bescheid sagen wenn was nicht passt.
