### ISSUE TITLE
Deutsche API Translations

### ISSUE THREAD

**Issue by maluramichael** [calliope-edu/calliope-mini-python-editor#15]
@joernalraun ich hab jetzt deine neuste Typeshed File eingebaut und noch paar Probleme mit den Headern behoben. Optimal ist das auf jeden fall nicht. Hier muessen wir demnaechst die Erweiterung des Translators eimplanen. So in den Dateien herumwerkeln ist nicht wirklich gut :-)

<img width="529" alt="image" src="https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/8c0ebf1b-9990-4080-ab36-4d218e760d8e">

**Comment by joernalraun** [comment]
@maluramichael stimmt, ich sehe die neuen Übersetzungen gar nicht, anscheinend ist das alles wieder englisch geworden?

**Comment by maluramichael** [comment]
Ja es ist jetzt ein komischer Mix. Auf Staging sieht es so aus. Header und Summary sind super auf deutsch uebersetzt und kommen so aus Crowdin.
<img width="596" alt="image" src="https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/1696b2f0-5aff-48db-a059-1a1ce90db532">

Lokal und mit deiner neuen Typeshed File passt der Header und ein paar Examples aber die Summaries sind jetzt wieder auf Englisch.
<img width="653" alt="image" src="https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/b38df30c-d238-4e5c-9b42-988acf745219">

**Comment by maluramichael** [comment]
@joernalraun kannst du mal diese File in Crowdin importieren und die alte damit updaten? Da sind jetzt die neuen Pins mit drin.

[api.en.json](https://github.com/calliope-edu/calliope-mini-python-editor/files/13346573/api.en.json)

Dann koenntest du die noch uebersetzen und mir ein neuen Export schicken.

**Comment by joernalraun** [comment]
> @joernalraun kannst du mal diese File in Crowdin importieren und die alte damit updaten? Da sind jetzt die neuen Pins mit drin.
> 
> [api.en.json](https://github.com/calliope-edu/calliope-mini-python-editor/files/13346573/api.en.json)
> 
> Dann koenntest du die noch uebersetzen und mir ein neuen Export schicken.
@maluramichael 
Mache ich! Das sind nun allerdings 27 Seiten, die zu übersetzen sind... Egal, geht fix. Die en Seite hatte allerdings Fehler drin (da waren falsche Links und noch ein paar falsche Zeichen drin, das schien die vorletzte oder so gewesen zu sein). Die neue davon schicke ich ebenfalls mit.

**Comment by maluramichael** [comment]
@joernalraun hab jetzt deine neuesten Translations aus Crowdin importiert.
