### ISSUE TITLE
Production Release

### ISSUE THREAD

**Issue by maluramichael** [calliope-edu/calliope-mini-python-editor#16]
Ich bin gerade dabei alle Repos anzugleichen und so langsam einen Prod Release zu fahren. Habt ihr noch was was ganz dringend mit rein muss? Ansonsten kann ich auch noch einen Release danach fahren.

@joernalraun @fabianhugo

**Comment by joernalraun** [comment]
@maluramichael ich hatte eigentlich nur auf die deutsche API gehofft, der Rest ist ziemlich gut!

**Comment by maluramichael** [comment]
Was denkst du? Soll ich die "alte" Translation nochmal nutzen, dann waeren nur die Examples nach dem aufklappen nicht uebersetzt. Der Rest kaeme ja dann so aus dem Crowdin Projekt.

**Comment by maluramichael** [comment]
Ich musste jetzt mal den Editor releasen. Ich versuch schon die ganze Zeit die e2e Tests zu fixen aber ich weiss nicht warum die Failen. Das sieht mir bisschen nach einem Timing Problem aus und nicht nach einem richtigen Fehler.

https://python.calliope.cc/ der Editor ist schon mal aktualisiert. Jetzt kommt noch der Simulator.

**Comment by joernalraun** [comment]
> Was denkst du? Soll ich die "alte" Translation nochmal nutzen, dann waeren nur die Examples nach dem aufklappen nicht uebersetzt. Der Rest kaeme ja dann so aus dem Crowdin Projekt.

Ja, das war besser oder?

**Comment by maluramichael** [comment]
Finde ich schon.

**Comment by joernalraun** [comment]
Ok, dann lieber die alte Translation nehmen.

**Comment by maluramichael** [comment]
@joernalraun @fabianhugo gibt es aus eurer Sicht noch etwas dringendes was aktuell auf Production muss?
* https://github.com/calliope-edu/calliope-mini-python-editor/issues/13 das muesste eigentlich schon gemacht sein aber ich kann gerne nochmal die aktuellste HEX in den Simulator und den Editor packen
* https://github.com/calliope-edu/calliope-mini-python-editor/issues/14 hier war, wenn ich es richtig verstanden habe, nur noch das Problem mit dem `import calliopemini` offen welches ich behoben habe. Die anderen Punkte sind ja in Sanity/Crowdin. Die Klassen wollten wir ja weiterhin als MicroBitDigitalPin stehen lassen. Und die Pins 18 und RGB sind auch im Code drin.

**Comment by maluramichael** [comment]
Aktuellster Code ist jetzt auf Main. Bei Gelegenheit einfach testen und mir bescheid geben.
