### ISSUE TITLE
Weitere Ideen Link

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-python-editor#2]
Wenn man die Ideen ganz nach unten scrollt, steht da ein Link "Mehr Ideen", der hierhin gehen sollte:
https://calliope.cc/schulen/unterrichtsmaterial?schulstufe=sek1

**Comment by maluramichael** [comment]
![image](https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/bb580cd1-4839-4d64-b19c-638c7beae4b1)

hab den Link angepasst.
