### ISSUE TITLE
API Übersetzungen

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-python-editor#3]
Wo kann man die API-Texte übersetzen?

**Comment by fabianhugo** [comment]
![grafik](https://github.com/calliope-edu/calliope-mini-python-editor/assets/32654742/6aa26167-a4a3-4d65-9e2f-764582133dca)
in API/radio steht noch micro:bit

**Comment by joernalraun** [comment]
[typeshed.de.json.txt](https://github.com/calliope-edu/calliope-mini-python-editor/files/12578122/typeshed.de.json.txt)
Der aktuelle Stand hochgeladen als txt (gab ansonsten nen Fehler), einfach .txt entfernen.

**Comment by maluramichael** [comment]
@joernalraun das hier hat sich eigentlich auch schon erledigt oder?
