### ISSUE TITLE
Tool-Tipps Übersetzungen

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-python-editor#4]
Wo kann man die Tool-Tipps übersetzen?

**Comment by maluramichael** [comment]
Weisst du noch welche Tooltips du meintest? Ueber die hier haben wir ja gesprochen 
<img width="813" alt="image" src="https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/13d41105-e30a-4c99-99a5-b1edde3c142b">

**Comment by joernalraun** [comment]
Die meinte ich! :)
