### ISSUE TITLE
add motor driver pins, add motor driver reference

### ISSUE THREAD

**Issue by fabianhugo** [calliope-edu/calliope-mini-python-editor#6]
The pin names are:

pin_M0_SPEED
pin_M0_DIR

pin_M1_SPEED
pin_M1_DIR

pin_A0_SDA
pin_A0_SCL

pin_A1_RX
pin_A1_TX

pin_M_Mode

pin_RGB

pin3 ->  digital, analog and touch

pin16->  digital and analog

pin17 -> digital

Motor driver reference should implement makecode-like motor driver

**Comment by joernalraun** [comment]
Neue Pins:

pin_M0_SPEED
pin_M0_DIR

pin_M1_SPEED
pin_M1_DIR

pin_A0_SDA
pin_A0_SCL

pin_A1_RX
pin_A1_TX

pin_M_Mode

pin3 ->  digital, analog and touch

pin16->  digital and analog

pin17 -> digital

**Comment by joernalraun** [comment]
pin_RGB

**Comment by joernalraun** [comment]
pin3 should also be activated as a touch pin (currently this is shown as an error).

**Comment by maluramichael** [comment]
Sind die Pins alle digital oder manche analog? Ich denke mal die M0 und M1 Pins sind analog oder?

pin_M0_SPEED: MicroBitAnalogDigitalPin
pin_M0_DIR: MicroBitAnalogDigitalPin
pin_M1_SPEED: MicroBitAnalogDigitalPin
pin_M1_DIR: MicroBitAnalogDigitalPin
pin_A0_SDA: MicroBitDigitalPin
pin_A0_SCL: MicroBitDigitalPin
pin_A1_RX: MicroBitDigitalPin
pin_A1_TX: MicroBitDigitalPin
pin_M_Mode: MicroBitDigitalPin

Laut doc koennen die anlogen noch folgendes 
```
class MicroBitAnalogDigitalPin(MicroBitDigitalPin):
    """A pin with analog and digital features."""

    def read_analog(self) -> int:
        """Read the voltage applied to the pin.

Example: ``pin0.read_analog()``

:return: An integer between 0 (meaning 0V) and 1023 (meaning 3.3V)."""
```

**Comment by fabianhugo** [comment]
Danke für die Frage.
Die Motor Pins können tatsächlich alle kein analog_read. deshalb sind sie nur "digital". Analog schreiben können alle Pins auf dem Calliope mini, analog schreiben entspricht der Ausgabe eines PWM Signals.

**Comment by maluramichael** [comment]
Das sieht doch schon mal nicht schlecht aus oder?
![image](https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/07395e89-dd34-42ac-86b7-ee01b5f3e240)

Nur das schreiben hat keine Auswirkungen. Sollte das bereits funktionieren? 
![image](https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/8b23e270-a66f-45f8-9433-695f21ef1406)

**Comment by maluramichael** [comment]
Dann habt ihr oben noch geschrieben

```
pin3 -> digital, analog and touch

pin16-> digital and analog

pin17 -> digital
```

Heisst ich mach aus dem pin3 einfach ein Touch Pin. Aus 16 ein DigitalAnalog und 17 fuege ich hinzu.

**Comment by maluramichael** [comment]
pin3 mit Touch geht jetzt auch 
![image](https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/2f466f71-4ec3-4ec0-a112-da952f98595f)

**Comment by fabianhugo** [comment]
spitze! das sieht richtig gut aus. 
die Änderungen sind noch nicht bei staging oder? 
eine sache noch. bei dem Pin:     pin_M_Mode haben wir falsch kommuniziert, der sollte eigentlich:     pin_M_MODE heißen, also MODE in capital.

**Comment by maluramichael** [comment]
Passe ich an kein Problem. Update kommt dann zeitnah auf Staging

**Comment by fabianhugo** [comment]
Super, danke.

**Comment by maluramichael** [comment]
Code ist eingecheckt. Glaube aber das auf Staging noch der Cache aktiv ist. Noch seh ich die Changes nicht. Muss man beobachten.
