### ISSUE TITLE
Video Link

### ISSUE THREAD

**Issue by maluramichael** [calliope-edu/calliope-mini-python-editor#7]
@joernalraun habt ihr schon ein neues Video? Das Ticket ist bei mir noch offen. Drum frag ich mal hier nach :)

![image](https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/b3bbd715-04a5-4cf9-880e-8ea4babca8a1)

**Comment by joernalraun** [comment]
Kommt! ;)

**Comment by maluramichael** [comment]
@joernalraun soll ich das Ticket bei uns in Jira noch ein wenig nach hinten stellen?

**Comment by joernalraun** [comment]
Ja, bitte. Die anderen Sachen sind auch wichtiger. ;)
