### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-python-editor#8]
– Bei Language "Hilfe-übersetzen" Link löschen oder auf unsere Kontaktseite verlinken (was einfacher ist).
– Link zu https://microbit-micropython.readthedocs.io/en/v2-docs/ auf https://calliope.cc/programmieren/editoren/python/python-api verlinken

**Comment by maluramichael** [comment]
![image](https://github.com/calliope-edu/calliope-mini-python-editor/assets/1489383/c193bf03-b963-435a-8eba-8193dad60b5c)

Habe den Link eingebaut

**Comment by joernalraun** [comment]
Ah, this was about two different links!
One when selecting language (thiamine is to delete) and the other one is when clicking on the question mark and selecting „MicroPython documentation“.

**Comment by joernalraun** [comment]
Even if we are going to use crowdin, it might be better to not link to it...

**Comment by maluramichael** [comment]
Habs angepasst 👍🏻
