### ISSUE TITLE
AWS info

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-python-editor#9]
Any needs for this:
AWS CloudShell's compute environment, which is currently based on Amazon Linux 2 (AL2), is scheduled to begin migration to Amazon Linux 2023 (AL2023) in all Regions starting December 4, 2023. You will receive another notification with additional information closer to the migration date.

**Comment by maluramichael** [comment]
Glaub nicht dass das was mit uns zu tun hat. Wir nutzen bei AWS ja nur S3.
